name: Continuous integration

on:
  push:
    branches:
      - "feature/**"
      - "bugfix/**"
  pull_request:
    branches:
      - "feature/**"
      - "bugfix/**"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: npm run test
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
